language: node_js
node_js:
  - "0.10"
services:
  - mysql

before_script:
  - mysql -uroot < ./scripts/create_database.sql
  - npm install -g gulp
  - npm install
  - export NODE_ENV=test
  - gulp install
  - gulp db:migrate --env test
  - cd src && node server.js

script:
  - gulp test

after_failure:
  - echo "build failed"

after_success:
  - echo "done "

notifications:
  slack: ngacn:6HY5F4fqhrSPeGZi77QxTFVj
