language: node_js
node_js:
  - "0.10"
services:
  - mysql

before_script:
  - mysql -uroot < ./scripts/create_database.sql
  - npm install -g gulp
  - npm install forever -g
  - npm install
  - export NODE_ENV=test
  - gulp install
  - gulp db:migrate --env test
  - forever start src/server.js
  - forever list
  - forever logs 0

script:
  - gulp test

after_failure:
  - forever logs 0

after_success:
  - forever logs 0
  - echo "should deploy service to UAT env"
notifications:
  slack: ngacn:6HY5F4fqhrSPeGZi77QxTFVj
