language: node_js
node_js:
  - "0.10"
services:
  - mysql

before_script:
  - mysql -uroot < ./scripts/create_database.sql
  - npm install -g gulp
  - npm install pm2 -g
  - npm install
  - export NODE_ENV=test
  - gulp install
  - gulp db:migrate --env test
  - pm2 start src/server.js -l ~/server.log
  - cat ~/server-0.log

script:
  - gulp test

after_failure:
  - cat ~/server-0.log

after_success:
  - cat ~/server-0.log
  - echo "should deploy service to UAT env"
notifications:
  slack: ngacn:6HY5F4fqhrSPeGZi77QxTFVj
