language: node_js
node_js:
  - "0.10"
services:
  - mysql

before_script:
  - sleep 1

script:
  - npm test

after_failure:
  - cat ~/.forever/server.log

after_success:
  - echo "done"

notifications:
  slack: ngacn:g7UKlznzOydd9RD1fDwYjXLi
