# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: YoBook API List
# domain
host: localhost:9527
# Describe your paths here
paths:
  /healthcheck:
    get:
      tags:
        - system
      summary: èŽ·å–æœåŠ¡å™¨æ—¶é—´
      responses:
        200:
          description: æœåŠ¡å™¨æ­£å¸¸
  /wantedLists:
    get:
      tags:
        - wanted list
      summary: æŸ¥è¯¢ç”¨æˆ·çš„æ„¿æœ›å•ï¼Œ å¸¦æœ‰userIdå‚æ•°ï¼Œå¦‚æžœç”¨æˆ·ç™»å½•åŽï¼Œä¸å¸¦userIdå‚æ•°ï¼ŒåŠ ä¸Štokenå¯ä»¥æŸ¥è¯¢æœ¬ç”¨æˆ·çš„æ„¿æœ›å•
      parameters:
        - name: userId
          in: query
          description: è¢«æŸ¥è¯¢æ„¿æœ›å•çš„ç”¨æˆ·id
          type: string
      responses:
        200:
          description: æ‰§è¡ŒæˆåŠŸï¼Œè¿”å›žæ‰€æŸ¥è¯¢çš„æ„¿æœ›å•
          schema:
            type: array
            items:
              $ref: '#/definitions/WantedList'
        404:
          description: æ‰§è¡Œå¤±è´¥ï¼Œä¸ºæ‰¾åˆ°æ‰€æŸ¥è¯¢çš„æ„¿æœ›å•
          schema:
            $ref: '#/definitions/Error'
  /wantedLists/{wantedListId}:
    get:
      tags:
        - wanted list
      summary: æ ¹æ®wanted list idæŒ‡å®šæŸ¥è¯¢æ„¿æœ›å•
      parameters:
        - name: wantedListId
          in: path
          description: æ„¿æœ›å•id
          type: string
      responses:
        200:
          description: æ‰¾åˆ°æ„¿æœ›å•
          schema:
            $ref: '#/definitions/WantedList'
        404:
          description: æœªæ‰¾åˆ°æ„¿æœ›å•
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    properties:
      message:
        type: string
        description: é”™è¯¯ä¿¡æ¯æè¿°
  WantedList:
    properties:
      id: 
        type: integer
        description: ä¸»é”®id
      books:
        type: array
        items:
          $ref: '#/definitions/Book'
  Book:
    properties:
      id:
        type: string
        description: ä¹¦ç±å”¯ä¸€id
      sn:
        type: string
        description: åºåˆ—å·ï¼Œ å¯ä»¥å¡«å†™CN\ ISSN \ISBNç­‰
      name:
        type: string
        description: ä¹¦ç±åç§°
      summary:
        type: string
        descrition: ä¹¦ç±ç®€ä»‹
      userId:
        type: string
        description: è¯¥ä¹¦ç±æ‰€æœ‰è€…
      